name: 'Build Antora Site with Docker'
description: 'Build an Antora documentation site using Docker. This action runs Antora in a Docker container to generate your site from antora.yml or site.yml.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'book-open'  
  color: 'orange'
